"""Install UAOS for every project on this PC (U37). Dry run by default; `--apply` writes, `--check` reports drift.

What it installs (the user approved B77 on 2026-09-25):
1. A launcher `~/.uaos/uaos.py`, so `python ~/.uaos/uaos.py <command>` runs this repository's harness from any folder.
2. A marked rule block in each tool's global rules: ~/.claude/CLAUDE.md, ~/.codex/AGENTS.md, ~/.gemini/GEMINI.md.
3. Presence (attendance) hooks: Claude ~/.claude/settings.json, Codex ~/.codex/hooks.json (+ `codex_hooks = true`),
   Antigravity ~/.gemini/config/hooks.json. They do nothing outside a UAOS project (no `.coord/PLAN.md` above cwd).
4. The paid-scheduler block for Claude: `permissions.deny` for CronCreate, ScheduleWakeup and the remote triggers.
5. Optional, Windows only: the 24/7 sentinel for one project (`--register-sentinel PROJECT`), a logon task that
   starts `coord sentinel --loop` under pythonw. It makes no model calls.

Safety: every file is copied to ~/.uaos-backups/<time>/ before it changes; a JSON file that does not parse is left
alone; only UAOS's own entries are replaced or removed (`--uninstall`), everything else in those files stays.
The three rule files are generated by the global-rules canon (shared/global-rules, sync-global-rules.ps1). A block
written here is removed by that generator's next Apply unless the canon carries it too; `--check` shows that drift.
"""

from __future__ import annotations

import argparse
import json
import platform
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

REPO_ROOT = Path(__file__).resolve().parent.parent
RULE_BLOCK_SOURCE = REPO_ROOT / "uaos_everywhere" / "uaos_global_rule_block.md"
ADAPTER_SOURCE = {
    "claude": REPO_ROOT / "uaos_everywhere" / "adapters" / "claude.md",
    "codex": REPO_ROOT / "uaos_everywhere" / "adapters" / "codex.md",
    "antigravity": REPO_ROOT / "uaos_everywhere" / "adapters" / "antigravity.md",
}
BLOCK_BEGIN = "<!-- UAOS:BEGIN (install_uaos_everywhere.py; source uaos_everywhere/uaos_global_rule_block.md) -->"
BLOCK_END = "<!-- UAOS:END -->"
BLOCK_RE = re.compile(r"\n?<!-- UAOS:BEGIN[^\n]*-->\n.*?<!-- UAOS:END -->\n?", re.DOTALL)
CANON_GENERATED_MARKER = "<!-- GENERATED from English canonical rules "
# U90: since global-rules canon v6.0.0 the canon carries UAOS-RSI itself (core.md + adapters/*.md). The old note
# told agents to copy this portable block into the canon, which would duplicate the rules past its size cap.
NOTES = (
    "Where shared/global-rules (sync-global-rules.ps1) generates the three rule files, that canon owns them and "
    "carries UAOS-RSI in its core.md and adapters/*.md; this installer leaves them unchanged. Change the rules "
    "there, never by copying uaos_everywhere/uaos_global_rule_block.md into the canon.",
    "New sessions pick up rules and hooks; an already open session does not.",
)
HOOK_MARK = "coord presence"
# U103-O: the olla whole-read gates the installer adds when `olla` is on PATH; only these exact commands are ours.
OLLA_HOOKS = ("olla hook-read", "olla hook-shell")
DENY = ("CronCreate", "ScheduleWakeup", "mcp__Claude_Code_Remote__create_trigger", "mcp__Claude_Code_Remote__send_later")
AGY_GROUP = "uaos-presence"
STATE_FILE = "install_state.json"


@dataclass
class Change:
    target: str
    path: Path | None
    action: str  # CREATE, UPDATE, UNCHANGED, SKIP, REMOVE
    detail: str = ""
    new_text: str | None = None
    state: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {"target": self.target, "path": str(self.path) if self.path else None, "action": self.action,
                "detail": self.detail}


def _q(value: Path | str) -> str:
    return f'"{value}"'


_NEEDS_QUOTES = re.compile(r"[\s&()^%!;'\"`$]")


def _arg(value: Path | str) -> str:
    """A path every hook shell reads the same way: forward slashes, and quotes only when the path needs them.

    Claude Code runs hooks in bash (Git Bash on Windows) unless a hook sets `shell: powershell`; Codex and Antigravity
    do not document their shell. PowerShell reads a leading quoted string as a value, not a command, so an unquoted
    C:/.../python.exe is the one form that runs in bash, cmd and PowerShell alike.
    """
    text = str(value).replace("\\", "/")
    return f'"{text}"' if _NEEDS_QUOTES.search(text) else text


def uaos_command(python: str, launcher: Path) -> str:
    return f"{_arg(python)} {_arg(launcher)}"


def needs_quotes(python: str, launcher: Path) -> bool:
    return uaos_command(python, launcher).startswith('"')


def presence_command(python: str, launcher: Path, tool: str, state: str, ttl: int, say: str,
                     delta: bool = False) -> str:
    # U103: `delta` adds what the other tools changed since this tool last looked (per-prompt hooks only).
    return (f"{uaos_command(python, launcher)} coord presence --tool {tool} --state {state} --ttl {ttl} "
            f"--from-hook --say {say}" + (" --delta" if delta else ""))


def launcher_text(repo: Path) -> str:
    return (
        '"""UAOS launcher written by install_uaos_everywhere.py: runs the UAOS harness (v7_harness) from any folder.\n\n'
        # A Windows path in a docstring is read as escapes (C:\\Users → \\U…), so the comment shows it with slashes.
        f"Source repository: {repo.as_posix()}\n"
        'Moved the repository? Run the installer again from its new place.\n"""\n'
        "import sys\n\n"
        f"sys.path.insert(0, {str(repo)!r})\n"
        "from v7_harness.cli import main  # noqa: E402\n\n"
        "sys.exit(main())\n"
    )


# For the global-rules canon (a shared, pushed repository): no machine path, and the same text on every PC.
# `$HOME` expands in bash and in PowerShell, the shells the three tools run.
PORTABLE_COMMAND = 'python "$HOME/.uaos/uaos.py"'


def rule_block(python: str, launcher: Path, source: Path = RULE_BLOCK_SOURCE, *, portable: bool = False,
               adapter: Path | None = None) -> str:
    """Render byte-identical common invariants followed by one tool's small adapter."""
    command = PORTABLE_COMMAND if portable else uaos_command(python, launcher)
    body = source.read_text(encoding="utf-8").strip().replace("{uaos}", command)
    if adapter is not None:
        body += "\n\n" + adapter.read_text(encoding="utf-8").strip().replace("{uaos}", command)
    return f"{BLOCK_BEGIN}\n{body}\n{BLOCK_END}\n"


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def _is_canon_generated(text: str) -> bool:
    """Accept the legacy marker or the generator's exact title/blank/marker header."""
    lines = text.lstrip("\ufeff").splitlines()
    if lines and lines[0].startswith(CANON_GENERATED_MARKER):
        return True
    return (
        len(lines) >= 3
        and lines[0] in {"# Antigravity Global Rules", "# Codex Global Rules", "# Claude Global Rules"}
        and lines[1] == ""
        and lines[2].startswith(CANON_GENERATED_MARKER)
    )


def _with_block(text: str | None, block: str | None) -> str:
    text = text or ""
    stripped = BLOCK_RE.sub("\n", text).rstrip("\n")
    if block is None:
        return (stripped + "\n") if stripped else ""
    return (stripped + "\n\n" if stripped else "") + block


def _load_json(path: Path) -> tuple[dict[str, Any] | None, str]:
    text = _read(path)
    if text is None or not text.strip():
        return {}, ""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        return None, f"not valid JSON ({exc.msg} at line {exc.lineno}); left as is"
    if not isinstance(data, dict):
        return None, "not a JSON object; left as is"
    return data, ""


def _strip_uaos_hooks(groups: list[Any]) -> list[Any]:
    kept = []
    for group in groups:
        if not isinstance(group, dict) or not isinstance(group.get("hooks"), list):
            kept.append(group)
            continue
        hooks = [h for h in group["hooks"] if not (isinstance(h, dict) and ((HOOK_MARK in str(h.get("command", ""))
                                                   and "uaos.py" in str(h.get("command", "")))
                                                   or h.get("command") in OLLA_HOOKS))]
        if hooks:
            kept.append({**group, "hooks": hooks})
    return kept


def _merge_hooks(data: dict[str, Any], wanted: dict[str, list[dict[str, Any]]], uninstall: bool) -> dict[str, Any]:
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    merged = dict(hooks)
    for event in set(merged) | set(wanted):
        groups = _strip_uaos_hooks(list(merged.get(event) or []))
        if not uninstall and event in wanted:
            groups.extend(wanted[event])
        if groups:
            merged[event] = groups
        else:
            merged.pop(event, None)
    result = dict(data)
    if merged or "hooks" in data:
        # A file that had `"hooks": {}` keeps it after an uninstall.
        result["hooks"] = merged
    return result


def _json_change(target: str, path: Path, before: dict[str, Any], after: dict[str, Any], existed: bool,
                 state: dict[str, Any] | None = None) -> Change:
    if before == after:
        return Change(target, path, "UNCHANGED")
    return Change(target, path, "UPDATE" if existed else "CREATE",
                  new_text=json.dumps(after, ensure_ascii=False, indent=2) + "\n", state=state or {})


def _text_change(target: str, path: Path, before: str | None, after: str, detail: str = "") -> Change:
    if (before or "") == after:
        return Change(target, path, "UNCHANGED", detail)
    if not after and before is not None:
        return Change(target, path, "UPDATE", detail or "block removed; the file is now empty", new_text="")
    return Change(target, path, "UPDATE" if before is not None else "CREATE", detail, new_text=after)


def plan(home: Path, python: str, *, repo: Path = REPO_ROOT, rules: bool = True, extra_rules: tuple[Path, ...] = (),
         portable: bool = False,
         enable_codex_hooks: bool = True, uninstall: bool = False) -> list[Change]:
    """Every change the install (or uninstall) would make, without writing anything."""
    home = Path(home)
    uaos_dir = home / ".uaos"
    launcher = uaos_dir / "uaos.py"
    state = _load_json(uaos_dir / STATE_FILE)[0] or {}
    changes: list[Change] = []
    block = None if uninstall else rule_block(python, launcher, portable=portable)
    shell_note = ("the Python or home path has spaces: the command is quoted, which bash and cmd run but a PowerShell "
                  "hook shell does not (it needs `& ` in front)") if needs_quotes(python, launcher) and not uninstall else ""

    if uninstall:
        changes.append(Change("launcher", launcher, "REMOVE" if launcher.exists() else "UNCHANGED"))
    else:
        # U48-R1: once a versioned runtime is current, the launcher follows it; writing the repo launcher here would
        # put the worktree back on sys.path and undo the install.
        from v7_harness import runtime_install
        wanted = (runtime_install.launcher_text() if runtime_install.read_current(home).get("version")
                  else launcher_text(repo))
        changes.append(_text_change("launcher", launcher, _read(launcher), wanted))

    tools = {
        "claude": home / ".claude",
        "codex": home / ".codex",
        "antigravity": home / ".gemini",
    }
    rule_paths = {"claude": tools["claude"] / "CLAUDE.md", "codex": tools["codex"] / "AGENTS.md",
                  "antigravity": tools["antigravity"] / "GEMINI.md"}

    for tool, folder in tools.items():
        if not folder.is_dir():
            changes.append(Change(f"{tool} (all)", folder, "SKIP", "tool folder not found: not installed for this user"))
            continue
        if rules:
            path = rule_paths[tool]
            current_rules = _read(path)
            if current_rules is not None and _is_canon_generated(current_rules):
                # The canon generator owns the complete file. A second block writer made generator Check and this
                # installer's --check mutually exclusive (U65-G); hooks and runtime remain this installer's scope.
                changes.append(Change(f"{tool} rules", path, "UNCHANGED",
                                      "global-rules canon owns this generated file"))
            else:
                tool_block = None if uninstall else rule_block(
                    python, launcher, portable=portable, adapter=ADAPTER_SOURCE[tool]
                )
                changes.append(_text_change(f"{tool} rules", path, current_rules,
                                            _with_block(current_rules, tool_block),
                                            "portable UAOS-RSI block (no global-rules canon owns this file)"))
        if tool == "claude":
            path = folder / "settings.json"
            data, problem = _load_json(path)
            if data is None:
                changes.append(Change("claude settings", path, "SKIP", problem))
            else:
                added = [name for name in DENY if name not in (data.get("permissions") or {}).get("deny", [])]
                wanted = {
                    # SessionStart stdout becomes context: one line, only inside a UAOS project.
                    "SessionStart": [{"hooks": [{"type": "command", "timeout": 10, "command": presence_command(
                        python, launcher, "claude", "ACTIVE", 3600, "brief")}]}],
                    # UserPromptSubmit stdout rides on the prompt: only a P1 hand-off while Codex is away (U38).
                    "UserPromptSubmit": [{"hooks": [{"type": "command", "timeout": 10, "command": presence_command(
                        python, launcher, "claude", "ACTIVE", 3600, "p1", delta=True)}]}],
                    "SessionEnd": [{"hooks": [{"type": "command", "timeout": 10, "command": presence_command(
                        python, launcher, "claude", "ABSENT", 86400, "none")}]}],
                }
                if shutil.which("olla"):
                    wanted["PreToolUse"] = [{"matcher": "Read", "hooks": [
                        {"type": "command", "timeout": 10, "command": OLLA_HOOKS[0]}]}]
                after = _merge_hooks(data, wanted, uninstall)
                permissions = dict(after.get("permissions") or {})
                deny = list(permissions.get("deny") or [])
                if uninstall:
                    ours = state.get("claude_deny_added", [])
                    deny = [name for name in deny if name not in ours]
                else:
                    deny.extend(added)
                if deny:
                    permissions["deny"] = deny
                else:
                    permissions.pop("deny", None)
                if permissions:
                    after["permissions"] = permissions
                else:
                    after.pop("permissions", None)
                keep = sorted(set(state.get("claude_deny_added", [])) | set(added))
                changes.append(_json_change("claude settings", path, data, after, path.exists(),
                                            {"claude_deny_added": [] if uninstall else keep}))
                changes[-1].detail = changes[-1].detail or shell_note
        elif tool == "codex":
            path = folder / "hooks.json"
            data, problem = _load_json(path)
            if data is None:
                changes.append(Change("codex hooks", path, "SKIP", problem))
            else:
                wanted = {
                    "SessionStart": [{"hooks": [{"type": "command", "timeout": 10, "command": presence_command(
                        python, launcher, "codex", "ACTIVE", 3600, "brief")}]}],
                    "UserPromptSubmit": [{"hooks": [{"type": "command", "timeout": 10, "command": presence_command(
                        python, launcher, "codex", "ACTIVE", 3600, "none", delta=True)}]}],
                }
                if shutil.which("olla"):
                    wanted["PreToolUse"] = [{"matcher": "Bash", "hooks": [
                        {"type": "command", "timeout": 10, "command": OLLA_HOOKS[1]}]}]
                changes.append(_json_change("codex hooks", path, data, _merge_hooks(data, wanted, uninstall),
                                            path.exists()))
                changes[-1].detail = changes[-1].detail or shell_note
            if enable_codex_hooks:
                changes.append(_codex_feature_change(folder / "config.toml", uninstall, state))
        elif tool == "antigravity":
            path = folder / "config" / "hooks.json"
            data, problem = _load_json(path)
            if data is None:
                changes.append(Change("antigravity hooks", path, "SKIP", problem))
            else:
                after = dict(data)
                if uninstall:
                    after.pop(AGY_GROUP, None)
                else:
                    # Antigravity runs hooks inside ~/.gemini/config (antigravity-cli#1005); --from-hook reads
                    # workspacePaths from stdin instead. It reads a JSON result on stdout: {} or, when its UAOS line
                    # changed, injectSteps with that line (U95-A; before, it always printed {} and learned nothing).
                    after[AGY_GROUP] = {"enabled": True, "PreInvocation": [{"type": "command", "command": presence_command(
                        python, launcher, "antigravity", "ACTIVE", 3600, "agy", delta=True)}]}
                changes.append(_json_change("antigravity hooks", path, data, after, path.exists()))
                changes[-1].detail = changes[-1].detail or shell_note

    for path in extra_rules:
        path = Path(path)
        changes.append(_text_change("extra rules", path, _read(path), _with_block(_read(path), block),
                                    "requested with --rules-file"))
    return changes


# Codex 0.157.1 (`codex features list`, 2026-09-28) names the hooks feature `hooks` (stable) and no longer lists
# `codex_hooks`, the name earlier installs wrote. Either spelling set to true counts; a new line uses the current name.
CODEX_HOOKS_KEY = "hooks"
_CODEX_HOOKS_KEYS = r"(?:hooks|codex_hooks)"


def _codex_feature_change(path: Path, uninstall: bool, state: dict[str, Any]) -> Change:
    text = _read(path)
    current = text or ""
    on = re.search(rf"(?m)^\s*{_CODEX_HOOKS_KEYS}\s*=\s*true\s*$", current)
    off = re.search(rf"(?m)^\s*{_CODEX_HOOKS_KEYS}\s*=\s*false\s*$", current)
    if uninstall:
        # Installs before the rename recorded only codex_hooks_added, and they wrote codex_hooks.
        added = state.get("codex_hooks_line", "codex_hooks")
        line = re.compile(rf"(?m)^\s*{re.escape(added)}\s*=\s*true\s*\n?")
        if state.get("codex_hooks_added") and line.search(current):
            return Change("codex hooks feature", path, "UPDATE", "removed the line this installer added",
                          new_text=line.sub("", current, count=1), state={"codex_hooks_added": False})
        return Change("codex hooks feature", path, "UNCHANGED", "left as it was before the install")
    if on:
        return Change("codex hooks feature", path, "UNCHANGED", "hooks feature already true")
    if off:
        return Change("codex hooks feature", path, "SKIP", "hooks feature = false was set by hand; left as is")
    if re.search(r"(?m)^\[features\]\s*$", current):
        after = re.sub(r"(?m)^\[features\]\s*$", f"[features]\n{CODEX_HOOKS_KEY} = true", current, count=1)
    else:
        after = current.rstrip("\n") + ("\n\n" if current.strip() else "") + f"[features]\n{CODEX_HOOKS_KEY} = true\n"
    return Change("codex hooks feature", path, "UPDATE" if text is not None else "CREATE",
                  "Codex runs hooks.json only with this flag (Codex may ask to trust the new hook)", new_text=after,
                  state={"codex_hooks_added": True, "codex_hooks_line": CODEX_HOOKS_KEY})


def apply(changes: list[Change], home: Path, backup_root: Path | None = None) -> dict[str, Any]:
    home = Path(home)
    stamp = time.strftime("%Y%m%d-%H%M%S")
    backup_dir = (backup_root or home / ".uaos-backups") / stamp
    written, backed_up = [], []
    state_path = home / ".uaos" / STATE_FILE
    state = _load_json(state_path)[0] or {}
    for change in changes:
        if change.action not in ("CREATE", "UPDATE", "REMOVE") or change.path is None:
            continue
        if change.path.exists():
            relative = change.path.relative_to(home) if change.path.is_relative_to(home) else Path(change.path.name)
            target = backup_dir / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(change.path, target)
            backed_up.append(str(target))
        if change.action == "REMOVE":
            change.path.unlink()
        else:
            change.path.parent.mkdir(parents=True, exist_ok=True)
            change.path.write_text(change.new_text or "", encoding="utf-8")
        written.append(str(change.path))
        state.update(change.state)
    if written:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state["installed_at"] = stamp
        state["repo"] = str(REPO_ROOT)
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"written": written, "backups": backed_up, "backup_dir": str(backup_dir) if backed_up else None}


# ---------------------------------------------------------------- 24/7 sentinel (Windows)


def _task_name(project: Path) -> str:
    return "UAOS Sentinel " + re.sub(r"[^A-Za-z0-9_.-]+", "_", Path(project).name)[:60]


def sentinel_cmd_text(project: Path, python: str, launcher: Path) -> str:
    pythonw = Path(python).with_name("pythonw.exe")
    runner = pythonw if pythonw.exists() else Path(python)
    log = Path(project) / ".work" / "sentinel" / "sentinel.log"
    return (
        "@echo off\r\n"
        f"rem UAOS 24/7 sentinel for {project} (install_uaos_everywhere.py). Local checks only, no model calls.\r\n"
        f'start "" {_q(runner)} {_q(launcher)} coord sentinel --project {_q(project)} --loop --interval 60 '
        f"--ring --write-brief --log {_q(log)}\r\n"
    )


def register_sentinel(project: Path, home: Path, python: str, *, run: Callable[..., Any] = subprocess.run,
                      system: str | None = None, dry_run: bool = True, remove: bool = False) -> dict[str, Any]:
    """A logon task (Task Scheduler) that starts the sentinel loop; the loop refuses to run twice for one project."""
    system = system or platform.system()
    project = Path(project).resolve()
    if system != "Windows":
        return {"ok": False, "error": "WINDOWS_ONLY: on Linux/macOS use a systemd user unit or launchd agent "
                                      "that runs `coord sentinel --loop` (docs/39)"}
    if not remove and not (project / ".coord" / "PLAN.md").is_file():
        return {"ok": False, "error": f"NOT_A_UAOS_PROJECT: {project} has no .coord/PLAN.md (run `coord init`)"}
    home = Path(home)
    launcher = home / ".uaos" / "uaos.py"
    cmd_path = home / ".uaos" / f"sentinel_{re.sub(r'[^A-Za-z0-9_.-]+', '_', project.name)}.cmd"
    name = _task_name(project)
    if remove:
        commands = [["schtasks", "/Delete", "/TN", name, "/F"]]
    else:
        # /TR is limited to 261 characters, so the task runs a short .cmd that holds the long command line.
        commands = [["schtasks", "/Create", "/TN", name, "/TR", _q(cmd_path), "/SC", "ONLOGON", "/RL", "LIMITED", "/F"],
                    ["schtasks", "/Run", "/TN", name]]
    if dry_run:
        return {"ok": True, "dry_run": True, "task": name, "cmd_file": str(cmd_path), "commands": commands}
    results = []
    if not remove:
        cmd_path.parent.mkdir(parents=True, exist_ok=True)
        cmd_path.write_text(sentinel_cmd_text(project, python, launcher), encoding="utf-8")
    for command in commands:
        done = run(command, capture_output=True, text=True)
        results.append({"command": command[:3], "returncode": done.returncode,
                        "output": ((done.stdout or "") + (done.stderr or "")).strip()[:300]})
        if done.returncode != 0:
            break
    ok = all(item["returncode"] == 0 for item in results)
    if remove and cmd_path.exists():
        cmd_path.unlink()
    advice = None
    if not ok and not remove:
        advice = ("Task Scheduler refused (a logon task may need an administrator prompt). Either run this again from "
                  "an administrator terminal, or put a shortcut to the .cmd file in shell:startup")
    return {"ok": ok, "task": name, "cmd_file": str(cmd_path), "results": results, "advice": advice}


# U91: the query uses PowerShell property names, which (unlike schtasks CSV headers) are not translated.
SENTINEL_TASK_QUERY = (
    "Get-ScheduledTask | ForEach-Object { [pscustomobject]@{ name = $_.TaskName; "
    "run = (($_.Actions | ForEach-Object { \"$($_.Execute) $($_.Arguments)\" }) -join ' | ') } } "
    "| ConvertTo-Json -Compress"
)
STALE_SENTINEL_ADVICE = (
    "Replace it: run this installer with --register-sentinel <project> --apply (the runtime sentinel at every logon), "
    "then delete the old task in Task Scheduler. Changing scheduled tasks waits for the user."
)


def stale_sentinel_tasks(*, run: Callable[..., Any] = subprocess.run, system: str | None = None) -> list[dict[str, str]] | None:
    """U91: scheduled tasks that start `coord sentinel` from a checkout instead of the installed runtime.

    Seen 2026-09-29: a hand-made "UAOS Sentinel 30m" task ran `python -m v7_harness.cli coord sentinel` in the desk
    checkout, dozens of merges behind, so the U88 P1 fix never reached the always-on sentinel, and its loop lock made
    the runtime sentinel skip with ALREADY_RUNNING. Only the launcher (~/.uaos/uaos.py, through the sentinel_*.cmd this
    installer writes) follows reinstalls. None means the query failed: unknown, never reported as clean.
    """
    system = system or platform.system()
    if system != "Windows":
        return []
    try:
        # 60 s: Get-ScheduledTask over a few hundred tasks took about 2 s here; the margin covers a cold PowerShell.
        done = run(["powershell", "-NoProfile", "-Command", SENTINEL_TASK_QUERY], capture_output=True, text=True,
                   timeout=60)
    except (OSError, subprocess.SubprocessError):
        return None
    if done.returncode != 0 or not (done.stdout or "").strip():
        return None
    try:
        data = json.loads(done.stdout)
    except json.JSONDecodeError:
        return None
    # ConvertTo-Json writes a single task as an object, several as a list.
    tasks = data if isinstance(data, list) else [data]
    stale = []
    for task in tasks:
        if not isinstance(task, dict):
            continue
        command = str(task.get("run") or "")
        if "coord sentinel" in command and "uaos.py" not in command:
            stale.append({"name": str(task.get("name")), "run": command[:300]})
    return stale


# ---------------------------------------------------------------- entry point


def _report(changes: list[Change]) -> list[dict[str, Any]]:
    return [change.as_dict() for change in changes]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="install_uaos_everywhere",
        description="Install UAOS rules, attendance hooks and the paid-scheduler block for every project on this PC. "
                    "Without --apply nothing is written.")
    parser.add_argument("--apply", action="store_true", help="Write the changes (backups first)")
    parser.add_argument("--check", action="store_true", help="Exit 1 if anything is missing or drifted")
    parser.add_argument("--uninstall", action="store_true", help="Remove only what UAOS added (with --apply)")
    parser.add_argument("--no-rules", action="store_true", help="Leave the three global rule files alone")
    parser.add_argument("--rules-file", action="append", default=[], type=Path,
                        help="Also put the block into this file (e.g. the global-rules canon source); repeatable")
    parser.add_argument("--no-codex-feature", action="store_true", help="Do not set codex_hooks = true")
    parser.add_argument("--portable", action="store_true",
                        help='Write the rule block with python "$HOME/.uaos/uaos.py" instead of this PC\'s paths '
                             "(for the shared global-rules canon)")
    parser.add_argument("--register-sentinel", type=Path, default=None, metavar="PROJECT",
                        help="Windows: start the 24/7 sentinel for PROJECT at every logon (with --apply)")
    parser.add_argument("--unregister-sentinel", type=Path, default=None, metavar="PROJECT")
    parser.add_argument("--home", type=Path, default=Path.home(), help=argparse.SUPPRESS)
    parser.add_argument("--python", default=sys.executable, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8")
            except (ValueError, OSError):
                pass

    changes = plan(args.home, args.python, rules=not args.no_rules, extra_rules=tuple(args.rules_file),
                   portable=args.portable,
                   enable_codex_hooks=not args.no_codex_feature, uninstall=args.uninstall)
    pending = [c for c in changes if c.action in ("CREATE", "UPDATE", "REMOVE")]
    output: dict[str, Any] = {"mode": "apply" if args.apply else ("check" if args.check else "dry-run"),
                              "changes": _report(changes)}
    code = 0
    if args.check:
        output["drift"] = [c.target for c in pending]
        code = 1 if pending else 0
        # U91: scheduled tasks belong to this PC's real user; a test or staging --home has none to check.
        if Path(args.home).resolve() == Path.home().resolve():
            stale = stale_sentinel_tasks()
            if stale is None:
                output["sentinel_tasks"] = "UNKNOWN"
            elif stale:
                output["drift"] += [f"stale sentinel task: {task['name']}" for task in stale]
                output["stale_sentinel_advice"] = STALE_SENTINEL_ADVICE
                code = 1
    elif args.apply:
        output["applied"] = apply(changes, args.home)
    else:
        output["next"] = "nothing was written; run again with --apply"
    sentinel_project = args.register_sentinel or args.unregister_sentinel
    if sentinel_project is not None:
        output["sentinel"] = register_sentinel(sentinel_project, args.home, args.python, dry_run=not args.apply,
                                               remove=args.unregister_sentinel is not None)
        if not output["sentinel"].get("ok"):
            code = code or 1
    output["notes"] = list(NOTES)
    print(json.dumps(output, ensure_ascii=False, indent=2))
    return code
